# Generated by Django 3.0.8 on 2020-07-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDNA',
            fields=[
                ('Save_Key', models.AutoField(primary_key=True, serialize=False, verbose_name='Save Key:')),
                ('TiltStrng', models.CharField(max_length=1000, verbose_name='Tilt (Tl):')),
                ('RollStrng', models.CharField(max_length=1000, verbose_name='Roll (Rl):')),
                ('TwistStrng', models.CharField(max_length=1000, verbose_name='Twist (Tw):')),
                ('ShiftStrng', models.CharField(max_length=1000, verbose_name='Shift (Sh):')),
                ('SlideStrng', models.CharField(max_length=1000, verbose_name='Slide (Sl):')),
                ('RiseStrng', models.CharField(max_length=1000, verbose_name='Rise (Rs):')),
                ('sMax', models.CharField(max_length=1000, verbose_name='Max S (MaxS):')),
                ('Lk', models.CharField(max_length=1000, verbose_name='Lk (Lk):')),
                ('Nuc', models.CharField(max_length=1000, verbose_name='Nuc (Nuc):')),
                ('V1Strng', models.CharField(max_length=1000, verbose_name='V1 (V1):')),
                ('V2Strng', models.CharField(max_length=1000, verbose_name='V2 (V2):')),
                ('IsNucStrng', models.CharField(max_length=1000, verbose_name='Cores (Cs):')),
                ('Geometry', models.CharField(default='Default', max_length=17)),
            ],
        ),
    ]
